# Generated by Django 3.0.8 on 2020-09-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caster', '0002_caster_url_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='caster',
            name='stream_delay',
            field=models.FloatField(blank=True, default=0, verbose_name='Your Stream Delay (in seconds)'),
        ),
    ]
